name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v5.0.0"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/starling_home_hub/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/starling_home_hub"
          zip starling_home_hub.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/starling_home_hub/starling_home_hub.zip
